name       : gnumeric
version    : 1.12.37
release    : 16
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gnumeric/1.12/gnumeric-1.12.37.tar.xz : 40371b9587857deefb0d1df950c3e02228d3f9b56def2e3aa86736ee24292468
license    : GPL-2.0+
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - itstool
patterns   :
    - /usr/lib64/*.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
