name       : gnumeric
version    : 1.12.42
release    : 21
source     :
    - https://download.gnome.org/sources/gnumeric/1.12/gnumeric-1.12.42.tar.xz : 54def8f93ab4858e2ed6499e2731c4393c1e94993696c944bd755a7a0879146d
license    : GPL-2.0-only
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - itstool
patterns   :
    - /usr/lib64/*.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
