name       : gnumeric
version    : 1.12.48
release    : 30
source     :
    - https://download.gnome.org/sources/gnumeric/1.12/gnumeric-1.12.48.tar.xz : 57cce33a41d34db81292e9eebae8b5046f30e5d919d848256fbb75bfc132a590
license    : GPL-2.0-or-later
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - gtk-doc
    - itstool
    - yelp-tools
patterns   :
    - /usr/lib64/*.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
