name       : gnumeric
version    : 1.12.53
release    : 38
source     :
    - https://download.gnome.org/sources/gnumeric/1.12/gnumeric-1.12.53.tar.xz : 5568e4c8dceabb9028f1361d1045522f95f0a71daa59e973cbdd2d39badd4f02
license    : GPL-2.0-or-later
homepage   : http://www.gnumeric.org/
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - gtk-doc
    - itstool
    - yelp-tools
patterns   :
    - /usr/lib64/*.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
