name       : gnumeric
version    : 1.12.41
release    : 20
source     :
    - https://download.gnome.org/sources/gnumeric/1.12/gnumeric-1.12.41.tar.xz : 66f6e665b7b6d708537295d8cbd00c5cb4efe31f605d5e646f38a7beab565969
license    : GPL-2.0-only
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - itstool
patterns   :
    - /usr/lib64/*.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
