name       : gnumeric
version    : 1.12.38
release    : 18
source     :
    - https://ftp.gnome.org/pub/GNOME/sources/gnumeric/1.12/gnumeric-1.12.38.tar.xz : 3435d7d93a47a32764b1ec2d03f7fbb348a97af52530815e49370803a1a69c65
license    : GPL-2.0
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - itstool
patterns   :
    - /usr/lib64/*.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
