name       : gnumeric
version    : 1.12.25
release    : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnumeric/1.12/gnumeric-1.12.25.tar.xz : 9709a8fccfc371a07b1590d037a43e525531d5a46f31c5c5fe223c6054cecdb6
license    : GPL-2.0+
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
patterns   :
    - /usr/lib64/libspreadsheet-1.12.24.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
