name       : gnumeric
version    : 1.12.35
release    : 15
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gnumeric/1.12/gnumeric-1.12.35.tar.xz : 77b1e3ce523578a807767ad71680fb865ac021d7bfadf93eada99ae094c06c0a
license    : GPL-2.0+
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - itstool
patterns   :
    - /usr/lib64/*.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
