name       : gnumeric
version    : 1.12.22
release    : 4
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/gnumeric/1.12/gnumeric-1.12.22.tar.xz : 3908cfd6520b599eefefe222aadeaa5126394b54d9a9a7f5e0f938eb674dcf47
license    : GPL-2.0+
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
clang      : no
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
