name       : gnumeric
version    : 1.12.49
release    : 31
source     :
    - https://download.gnome.org/sources/gnumeric/1.12/gnumeric-1.12.49.tar.xz : 91c072ec95c32e00b156ffe8015c93b32b8edf368f9041436193cfa32e84ed57
license    : GPL-2.0-or-later
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - gtk-doc
    - itstool
    - yelp-tools
patterns   :
    - /usr/lib64/*.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
