name       : gnumeric
version    : 1.12.52
release    : 36
source     :
    - https://download.gnome.org/sources/gnumeric/1.12/gnumeric-1.12.52.tar.xz : 73cf73049a22a1d828506275b2c9378ec37c5ff37b68bb1f2f494f0d6400823b
license    : GPL-2.0-or-later
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - gtk-doc
    - itstool
    - yelp-tools
patterns   :
    - /usr/lib64/*.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
