name       : gnumeric
version    : 1.12.34
release    : 13
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnumeric/1.12/gnumeric-1.12.34.tar.xz : 0b4920812d82ec4c25204543dff9dd3bdbac17bfaaabd1aa02d47fbe2981c725
license    : GPL-2.0+
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - itstool
patterns   :
    - /usr/lib64/*.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
