name       : gnumeric
version    : 1.12.55
release    : 43
source     :
    - https://download.gnome.org/sources/gnumeric/1.12/gnumeric-1.12.55.tar.xz : c69a09cd190b622acca476bbc3d4c03d68d7ccf59bba61bf036ce60885f9fb65
license    : GPL-2.0-or-later
homepage   : http://www.gnumeric.org/
summary    : GNOME Desktop spreadsheet application aiming for speed and lightness
component  : office
description: |
    GNOME Desktop spreadsheet application aiming for speed and lightness
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(libgoffice-0.10)
    - pkgconfig(libgsf-1)
    - pkgconfig(pygobject-3.0)
    - itstool
    - yelp-tools
patterns   :
    - /usr/lib64/*.so
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Fix appstream generation
    mv $installdir/usr/share/applications/{gnumeric.desktop,org.gnumeric.gnumeric.desktop}
